version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '8090:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - devops-2
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - devops-2
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: hng_devops_app
      POSTGRES_USER: starlingroot
      POSTGRES_PASSWORD: starlingroot
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devops-2
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - postgresdb
    networks:
      - devops-2
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - devops-2
volumes:
  postgres_data:
networks:
  devops-2:
    driver: bridge
